apiVersion: v2
appVersion: 2.14.1
description: A Jaeger Helm chart for Kubernetes
name: jaeger
type: application
version: 4.4.6
# CronJobs require v1.21
kubeVersion: ">= 1.21-0"
keywords:
  - jaeger
  - opentracing
  - tracing
  - instrumentation
home: https://jaegertracing.io
icon: https://www.jaegertracing.io/img/jaeger-icon-reverse-color.svg
sources:
  - https://hub.docker.com/u/jaegertracing/
maintainers:
  - name: mehta-ankit
    email: ankit.mehta@appian.com
  - name: mikelorant
    email: michael.lorant@fairfaxmedia.com.au
  - name: naseemkullah
    email: naseem@transit.app
  - name: pavelnikolov
    email: me@pavelnikolov.net
  - name: jkowall
    email: jkowall@kowall.net
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
