apiVersion: v2
appVersion: 2.14.1
description: A Jaeger Helm chart for Kubernetes
name: jaeger
type: application
version: 4.4.8
# Artifact Hub annotations
# The jaeger image is whitelisted from security scanning because the reported
# CVEs are in the upstream Alpine base image (OpenSSL libcrypto3/libssl3) and
# Go stdlib, not in this Helm chart. These will be resolved when the Jaeger
# project releases a new image with updated base packages.
annotations:
  artifacthub.io/images: |
    - name: jaeger
      image: jaegertracing/jaeger:2.14.1
      whitelisted: true
      ignored: true
# CronJobs require v1.21
kubeVersion: ">= 1.21-0"
keywords:
  - jaeger
  - opentracing
  - tracing
  - instrumentation
home: https://jaegertracing.io
icon: https://www.jaegertracing.io/img/jaeger-icon-reverse-color.svg
sources:
  - https://hub.docker.com/u/jaegertracing/
maintainers:
  - name: mehta-ankit
    email: ankit.mehta@appian.com
  - name: mikelorant
    email: michael.lorant@fairfaxmedia.com.au
  - name: naseemkullah
    email: naseem@transit.app
  - name: pavelnikolov
    email: me@pavelnikolov.net
  - name: jkowall
    email: jkowall@kowall.net
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
