apiVersion: v2
appVersion: 1.36.0
description: A Jaeger Helm chart for Kubernetes
name: jaeger
type: application
version: 0.57.0
keywords:
  - jaeger
  - opentracing
  - tracing
  - instrumentation
home: https://jaegertracing.io
icon: https://camo.githubusercontent.com/afa87494e0753b4b1f5719a2f35aa5263859dffb/687474703a2f2f6a61656765722e72656164746865646f63732e696f2f656e2f6c61746573742f696d616765732f6a61656765722d766563746f722e737667
sources:
  - https://hub.docker.com/u/jaegertracing/
maintainers:
  - name: dvonthenen
    email: david.vonthenen@dell.com
  - name: mehta-ankit
    email: ankit.mehta@appian.com
  - name: mikelorant
    email: michael.lorant@fairfaxmedia.com.au
  - name: naseemkullah
    email: naseem@transit.app
  - name: pavelnikolov
    email: pavel.nikolov@fairfaxmedia.com.au
dependencies:
  - name: cassandra
    version: 0.15.3
    repository: https://charts.helm.sh/incubator
    condition: provisionDataStore.cassandra
  - name: elasticsearch
    version: ^7.11.1
    repository: https://helm.elastic.co
    condition: provisionDataStore.elasticsearch
  - name: kafka
    version: ^14.9.1
    repository: https://charts.bitnami.com/bitnami
    condition: provisionDataStore.kafka
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.16.0
