{{- if .Values.collector.enabled -}}
{{- if eq .Values.storage.type "cassandra" -}}
{{- if .Values.storage.cassandra.schemaJobEnabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jaeger.fullname" . }}-cassandra-schema
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: cassandra-schema
{{- if .Values.schema.annotations }}
  annotations:
    {{- toYaml .Values.schema.annotations | nindent 4 }}
{{- end }}
spec:
  activeDeadlineSeconds: {{ .Values.schema.activeDeadlineSeconds }}
  template:
    metadata:
      name: {{ include "jaeger.fullname" . }}-cassandra-schema
{{- if .Values.schema.podAnnotations }}
      annotations:
        {{- toYaml .Values.schema.podAnnotations | nindent 8 }}
{{- end }}
{{- if .Values.schema.podLabels }}
      labels:
        {{- toYaml .Values.schema.podLabels | nindent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "jaeger.cassandraSchema.serviceAccountName" . }}
      {{- with .Values.schema.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "jaeger.fullname" . }}-cassandra-schema
        image: {{ .Values.schema.image }}:{{- include "jaeger.image.tag" . }}
        imagePullPolicy: {{ .Values.schema.pullPolicy }}
        env:
        {{- if .Values.schema.extraEnv }}
          {{- toYaml .Values.schema.extraEnv | nindent 10 }}
        {{- end }}
          {{ range $key, $value := .Values.schema.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{ end }}
          {{- include "cassandra.env" . | nindent 10 }}
          - name: CQLSH_HOST
            value: {{ template "cassandra.host" . }}
          {{ if .Values.storage.cassandra.tls.enabled }}
          - name: CQLSH_SSL
            value: "--ssl"
          {{- end }}
          - name: DATACENTER
            value: {{ .Values.cassandra.config.dc_name | quote }}
        {{- if .Values.storage.cassandra.keyspace }}
          - name: KEYSPACE
            value: {{ .Values.storage.cassandra.keyspace }}
        {{- end }}
        {{- if .Values.schema.resources }}
        resources:
        {{- toYaml .Values.schema.resources | nindent 10 }}
        {{- end }}
        {{- if or (.Values.schema.podSecurityContext) (.Values.podSecurityContext) }}
        securityContext:
        {{- merge .Values.podSecurityContext .Values.schema.podSecurityContext | toYaml | nindent 10 }}
        {{- end }}
        {{- if or (.Values.schema.extraConfigmapMounts) (.Values.storage.cassandra.tls.enabled) }}
        volumeMounts:
        {{- range .Values.schema.extraConfigmapMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
            readOnly: {{ .readOnly }}
        {{- end }}
        {{- if .Values.storage.cassandra.tls.enabled }}
          - name: {{ .Values.storage.cassandra.tls.secretName }}
            mountPath: "/root/.cassandra/ca-cert.pem"
            subPath: "ca-cert.pem"
            readOnly: true
          - name: {{ .Values.storage.cassandra.tls.secretName }}
            mountPath: "/root/.cassandra/client-cert.pem"
            subPath: "client-cert.pem"
            readOnly: true
          - name: {{ .Values.storage.cassandra.tls.secretName }}
            mountPath: "/root/.cassandra/client-key.pem"
            subPath: "client-key.pem"
            readOnly: true
          - name: {{ .Values.storage.cassandra.tls.secretName }}
            mountPath: "/root/.cassandra/cqlshrc"
            subPath: "cqlshrc"
            readOnly: true
        {{- end }}
        {{- end }}
      restartPolicy: OnFailure
      {{- if or (.Values.schema.podSecurityContext) (.Values.podSecurityContext) }}
      securityContext:
      {{- merge .Values.podSecurityContext .Values.schema.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      {{- if or (.Values.schema.extraConfigmapMounts) (.Values.storage.cassandra.tls.enabled) }}
      volumes:
      {{- range .Values.schema.extraConfigmapMounts }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap }}
      {{- end }}
      {{- if .Values.storage.cassandra.tls.enabled }}
        - name: {{ .Values.storage.cassandra.tls.secretName }}
          secret:
            secretName: {{ .Values.storage.cassandra.tls.secretName }}
      {{- end }}
      {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
