{{- if .Values.esLookback.enabled -}}
apiVersion: {{ include "common.capabilities.cronjob.apiVersion" $ }}
kind: CronJob
metadata:
  name: {{ include "jaeger.fullname" . }}-es-lookback
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: es-lookback
{{- if .Values.esLookback.annotations }}
  annotations:
    {{- toYaml .Values.esLookback.annotations | nindent 4 }}
{{- end }}
spec:
  concurrencyPolicy: {{ .Values.esLookback.concurrencyPolicy }}
  schedule: {{ .Values.esLookback.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.esLookback.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.esLookback.failedJobsHistoryLimit }}
  suspend: false
  jobTemplate:
    spec:
      {{- if .Values.esLookback.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.esLookback.activeDeadlineSeconds }}
      {{- end }}
      template:
        metadata:
          {{- if .Values.esLookback.podAnnotations }}
          annotations:
            {{- toYaml .Values.esLookback.podAnnotations | nindent 12 }}
          {{- end }}
          labels:
            {{- include "jaeger.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: es-lookback
            {{- if .Values.esLookback.podLabels }}
            {{- toYaml .Values.esLookback.podLabels | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ template "jaeger.esLookback.serviceAccountName" . }}
          {{- with .Values.esLookback.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.esLookback.podSecurityContext | nindent 12 }}
          restartPolicy: OnFailure
          {{- with .Values.esLookback.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.esLookback.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.esLookback.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          containers:
          - name: {{ include "jaeger.fullname" . }}-es-lookback
            securityContext:
              {{- toYaml .Values.esLookback.securityContext | nindent 14 }}
            image: "{{ .Values.esLookback.image }}:{{- include "jaeger.image.tag" . }}"
            imagePullPolicy: {{ .Values.esLookback.pullPolicy }}
            args:
              - lookback
              - {{ include "elasticsearch.client.url" . }}
            env:
              {{ include "elasticsearch.env" . | nindent 14 }}
              {{- if .Values.esLookback.extraEnv }}
                {{- toYaml .Values.esLookback.extraEnv | nindent 14 }}
              {{- end }}
            resources:
              {{- toYaml .Values.esLookback.resources | nindent 14 }}
            volumeMounts:
            {{- range .Values.esLookback.extraConfigmapMounts }}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
                subPath: {{ .subPath }}
                readOnly: {{ .readOnly }}
            {{- end }}
            {{- range .Values.esLookback.extraSecretMounts }}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
                subPath: {{ .subPath }}
                readOnly: {{ .readOnly }}
            {{- end }}
          volumes:
          {{- range .Values.esLookback.extraConfigmapMounts }}
            - name: {{ .name }}
              configMap:
                name: {{ .configMap }}
          {{- end }}
          {{- range .Values.esLookback.extraSecretMounts }}
            - name: {{ .name }}
              secret:
                secretName: {{ .secretName }}
        {{- end }}
{{- end -}}
