{{- if .Values.hotrod.enabled -}}
{{- if .Values.hotrod.ingress.enabled -}}
{{- $serviceName := include "jaeger.fullname" . -}}
{{- $servicePort := .Values.hotrod.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "jaeger.fullname" . }}-hotrod
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: hotrod
{{- if .Values.hotrod.ingress.annotations }}
  annotations:
    {{- toYaml .Values.hotrod.ingress.annotations | nindent 4 }}
{{- end }}
spec:
  rules:
    {{- range $host := .Values.hotrod.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}-hotrod
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.hotrod.ingress.tls }}
  tls:
    {{- toYaml .Values.hotrod.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
