{{- if .Values.query.ingress.enabled -}}
{{- $servicePort := .Values.query.service.port -}}
{{- $basePath := .Values.query.basePath -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "jaeger.query.name" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
  {{- if .Values.query.ingress.annotations }}
  annotations:
    {{- toYaml .Values.query.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.query.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $basePath }}
            backend:
              serviceName: {{ template "jaeger.query.name" $ }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.query.ingress.tls }}
  tls:
    {{- toYaml .Values.query.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
