{{- if .Values.userconfig -}}
# Generates a config map from a file provided by user via `--set-file userconfig=`
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: {{ include "jaeger.namespace" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
data:
  user-config.yaml: |
    {{- .Values.userconfig | nindent 4 }}
{{- end -}}
{{- if .Values.uiconfig -}}
{{- if .Values.userconfig }}
---
{{- end }}
# Generates a config map from a file provided by user via `--set-file uiconfig=`
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: {{ include "jaeger.namespace" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
data:
  ui-config.json: |
    {{- .Values.uiconfig | nindent 4 }}
{{- end -}}