{{- if .Values.jaeger.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jaeger.fullname" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: all-in-one
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
  {{- with include "jaeger.annotations" (dict "context" . "component" nil) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if hasKey .Values.jaeger "replicas" }}
  replicas: {{ .Values.jaeger.replicas }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "jaeger.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: all-in-one
  template:
    metadata:
      labels:
        {{- include "jaeger.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: all-in-one
{{- if .Values.jaeger.podLabels }}
        {{- toYaml .Values.jaeger.podLabels | nindent 8 }}
{{- end }}
      annotations:
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
    spec:
      {{- include "jaeger.imagePullSecrets" . | nindent 6 }}
      containers:
        - env:
          {{- if .Values.jaeger.extraEnv }}
            {{- toYaml .Values.jaeger.extraEnv | nindent 10 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.jaeger.securityContext | nindent 12 }}
          image: {{ include "jaeger.image" . }}
          imagePullPolicy: {{ .Values.jaeger.image.pullPolicy }}
          name: jaeger
          args:
            {{- if .Values.userconfig }}
            - "--config"
            - "/etc/jaeger/user-config.yaml"
            {{- end }}
            {{- range $arg := .Values.jaeger.args }}
            - "{{ tpl $arg $ }}"
            {{- end }}
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 16685
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 13133
              protocol: TCP
            - containerPort: 8888
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /status
              port: 13133
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: 13133
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      {{- with .Values.jaeger.resources }}
          resources:
        {{- toYaml . | nindent 12 }}
      {{- end }}
          volumeMounts:
        {{- if .Values.userconfig }}
            - name: user-config
              mountPath: /etc/jaeger/user-config.yaml
              subPath: user-config.yaml
        {{- end }}
        {{- if .Values.uiconfig }}
            - name: ui-config
              mountPath: /etc/jaeger/ui-config.json
              subPath: ui-config.json
        {{- end }}
        {{- with .Values.jaeger.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
        {{- end }}
      securityContext:
        {{- toYaml .Values.jaeger.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ template "jaeger.fullname" . }}
      volumes:
      {{- if .Values.userconfig }}
        - name: user-config
          configMap:
            name: user-config
      {{- end }}
      {{- if .Values.uiconfig }}
        - name: ui-config
          configMap:
            name: ui-config
      {{- end }}
      {{- with .Values.jaeger.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.jaeger.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jaeger.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jaeger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jaeger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
