{{- if .Values.jaeger.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jaeger.fullname" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: all-in-one
  {{- with include "jaeger.annotations" (dict "context" . "component" .Values.jaeger.serviceAccount.annotations) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.jaeger.serviceAccount.automountServiceAccountToken }}
{{- end -}}
