{{- if .Values.uiconfig -}}
# Generates a config map from a file provided by user via `--set-file uiconfig=`
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "jaeger.annotations" . | nindent 4 }}
  {{- end }}
data:
  ui-config.json: {{ toJson .Values.uiconfig | quote }}
{{- end -}}