apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger.fullname" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: all-in-one
    {{- if .Values.jaeger.service.labels }}
      {{- toYaml .Values.jaeger.service.labels | nindent 4 }}
    {{- end }}
  {{- with include "jaeger.annotations" (dict "context" . "component" .Values.jaeger.service.annotations) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.jaeger.service.type | default "ClusterIP" }}
  {{- if .Values.jaeger.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ toYaml .Values.jaeger.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    # Agent Ports
    - name: zk-compact-trft
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: config-rest
      port: 5778
      targetPort: 5778
    - name: jg-compact-trft
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: jg-binary-trft
      port: 6832
      protocol: UDP
      targetPort: 6832
    # Collector Ports
    - name: http-zipkin
      port: 9411
      targetPort: 9411
      appProtocol: http
    - name: grpc-http
      port: 14250
      targetPort: 14250
      appProtocol: grpc
    - name: c-tchan-trft
      port: 14267
      targetPort: 14267
    - name: http-c-binary-trft
      port: 14268
      targetPort: 14268
      appProtocol: http
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      appProtocol: grpc
    - name: otlp-http
      port: 4318
      targetPort: 4318
      appProtocol: http
    # Query Ports
    - name: http-query
      port: 16686
      targetPort: 16686
    - name: grpc-query
      port: 16685
      targetPort: 16685
    # Metrics Ports
    - name: internal-metrics
      port: 8888
      targetPort: 8888
      appProtocol: http
    - name: span-metrics
      port: 8889
      targetPort: 8889
      appProtocol: http
  {{- if .Values.jaeger.service.extraPorts }}
    # Additional Ports
  {{- range .Values.jaeger.service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- if .protocol }}
      protocol: {{ .protocol }}
  {{- end }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "jaeger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: all-in-one
